#include "lib/declarations.dl"
#include "lib/types.dl"

// https://etherscan.io/tx/0x97801ae54b460f009385602b806d6bc340da73c4925da06df56801d906762e6c#eventlog

// sc_erc20_transfer(x,z) :- sc_erc20_transfer(x, y), sc_erc20_transfer(y, z), x = "0x0000000000000000000000000000000000000000"


/* Fake deposit of tokens - source chain */

// bridge emitted event but tokens not moved
// fakeDepositTokens() :-
//     existe um evento emitido pela bridge
//     existe um evento emitido pelo contrato do token respetivo
//     ambos no mesmo bloco
    

// tokens transferred but tokens did not move
// fakeTokenDeposited()


/* Fake deposit of tokens - source chain */
